@AdHoc_SpeechSynthesizer_HostAddress = http://localhost:5032


### Get all available TTS models
GET https://localhost:7275/api/TtsModels
Accept: application/json


### Get all available voices
GET https://localhost:7275/api/TtsVoices
Accept: application/json


### Get voices for Windows
GET https://localhost:7275/api/TtsModels/D229008E-A9B5-410C-B794-274763DACA4E/voices
Accept: application/json

### Get voices for Azure
GET https://localhost:7275/api/TtsModels/7FF02809-B650-45C1-B4A8-3DE02DAEBC1C/voices
Accept: application/json


### Synthesize speech (System.Speech)
POST https://localhost:7275/api/Synthesis/from-ssml
Content-Type: application/json
Accept: audio/wav

{
  "ssmlContent": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<speak version=\"1.0\"\n       xmlns=\"http://www.w3.org/2001/10/synthesis\"\n       xml:lang=\"de-AT\">\n  <voice name=\"de-AT-JonasNeural\">\n    <p>\n      <s>Nächster Halt: Linz Hauptbahnhof.</s><break time=\"400ms\"/>\n      <s>Sie haben Anschluss zu den Linien\n          1<break time=\"300ms\"/>,\n          2<break time=\"300ms\"/>\n          und 43</s>\n    </p>\n  </voice>\n</speak>",
  "modelId": "D229008E-A9B5-410C-B794-274763DACA4E",
  "voiceId": null
}

### Synthesize speech with Azure specific content
POST https://localhost:7275/api/Synthesis/from-ssml
Content-Type: application/json
Accept: audio/wav

{
  "ssmlContent": "<speak version=\"1.0\" xmlns=\"http://www.w3.org/2001/10/synthesis\" xmlns:mstts=\"https://www.w3.org/2001/mstts\" xml:lang=\"en-US\"><voice name=\"en-US-AvaNeural\" mstts:visemeType=\"FacialExpression\"><mstts:express-as style=\"cheerful\">This should still pass validation although it uses Azure-specific tags.</mstts:express-as></voice></speak>",
  "modelId": "D229008E-A9B5-410C-B794-274763DACA4E",
  "voiceId": null
}

### Synthesize speech with invalid ssml (missing voice name attribute)
POST https://localhost:7275/api/Synthesis/from-ssml
Content-Type: application/json
Accept: audio/wav

{
  "ssmlContent": "<speak version=\"1.0\" xmlns=\"http://www.w3.org/2001/10/synthesis\" xml:lang=\"en-US\"><voice>Oops, no name attribute here.</voice></speak>",
  "modelId": "D229008E-A9B5-410C-B794-274763DACA4E",
  "voiceId": null
}

### Synthesize speech with invalid ssml (missing voice element)
POST https://localhost:7275/api/Synthesis/from-ssml
Content-Type: application/json
Accept: audio/wav

{
  "ssmlContent": "<speak xmlns=\"http://www.w3.org/2001/10/synthesis\">This SSML is missing a voice element.</speak>",
  "modelId": "D229008E-A9B5-410C-B794-274763DACA4E",
  "voiceId": null
}

### Synthesize speech with invalid ssml (speak is not root element)
POST https://localhost:7275/api/Synthesis/from-ssml
Content-Type: application/json
Accept: audio/wav

{
  "ssmlContent": "<div xmlns=\"http://www.w3.org/2001/10/synthesis\"><voice name=\"en-US-AvaNeural\">Wrong root element.</voice></div>",
  "modelId": "D229008E-A9B5-410C-B794-274763DACA4E",
  "voiceId": null
}


### Synthesize speech with invalid ssml (not well-formed)
POST https://localhost:7275/api/Synthesis/from-ssml
Content-Type: application/json
Accept: audio/wav

{
  "ssmlContent": "<speak xmlns=\"http://www.w3.org/2001/10/synthesis\"><voice name=\"en-US-AvaNeural\">This tag never closes</speak>",
  "modelId": "D229008E-A9B5-410C-B794-274763DACA4E",
  "voiceId": null
}

### Synthesize speech with invalid ssml (placeholder not replaced)
POST https://localhost:7275/api/Synthesis/from-ssml
Content-Type: application/json
Accept: audio/wav

{
  "ssmlContent": "<speak version=\"1.0\" xmlns=\"http://www.w3.org/2001/10/synthesis\" xml:lang=\"en-US\"><voice name=\"en-US-AvaNeural\">This tag never closes</speak>",
  "modelId": "D229008E-A9B5-410C-B794-274763DACA4E",
  "voiceId": null
}

### Synthesize speech with invalid ssml (placeholder not replaced)
POST https://localhost:7275/api/Synthesis/from-ssml
Content-Type: application/json
Accept: audio/wav
  
{
  "ssmlContent": "<speak version=\"1.0\" xmlns=\"http://www.w3.org/2001/10/synthesis\"><voice name=\"en-US-AvaNeural\">Hello <break time=\"1s\"></voice> World!</break></speak>",
  "modelId": "D229008E-A9B5-410C-B794-274763DACA4E",
  "voiceId": null
}



### Test with a specific voice
POST https://localhost:7275/api/Synthesis/from-ssml
Content-Type: application/json
Accept: audio/wav

{
  "ssmlContent": "<speak version='1.0' xml:lang='de-DE'><voice name='de-DE-ConradNeural'>Guten Tag! Wie geht es Ihnen?</voice></speak>",
  "modelId": "D229008E-A9B5-410C-B794-274763DACA4E",
  "voiceId": "5ECC5FE8-5D2D-4B82-AE2D-B974179B7167"
}

### Get all available message templates
GET https://localhost:7275/api/messagetemplates
Accept: application/json


### Synthesize speech from a template
POST https://localhost:7275/api/synthesis/from-template
Content-Type: application/json

{
  "templateId": "02e6224f-b912-49e4-8ea4-5b408e21c6d8",
  "modelId": "D229008E-A9B5-410C-B794-274763DACA4E",
  "voiceId": null,
  "refLocationNames": null,
  "platformNumbers": null,
  "routeNrs": [27],
  "frontTexts": null,
  "freeTexts": ["technischen Störungen"]
}

### Synthesize speech from a template with multiple values

POST https://localhost:7275/api/synthesis/from-template
Content-Type: application/json

{
  "templateId": "82a4a359-8a4d-4c95-bfa2-2231494203a4",
  "modelId": "D229008E-A9B5-410C-B794-274763DACA4E",
  "voiceId": null,
  "refLocationNames": ["Hauptbahnhof", "Rathausplatz"],
  "platformNumbers": [1, 3],
  "routeNrs": null,
  "frontTexts": null,
  "freeTexts": null
}





### Get all locations
GET https://localhost:7275/api/Location
Accept: application/json

### Get all RefLocationNames
GET https://localhost:7275/api/Location/RefLocationNames
Accept: application/json




### all platforms numbers
GET https://localhost:7275/api/Platform/platformnumbers
Accept: application/json




### All routes
GET https://localhost:7275/api/Route

### All RouteNrs
GET https://localhost:7275/api/Route/RouteNrs


### Get all target texts
GET https://localhost:7275/api/TargetText
Accept: application/json

### Get all target text FrontTexts
GET https://localhost:7275/api/TargetText/fronttexts
Accept: application/json
